### ISSUE TITLE
请问有计划原生支持Mac m1么？

### ISSUE THREAD

**Issue by TtlyLynzie** [tangshimin/typing-learner#101]
如题

**Comment by tangshimin** [comment]
暂时没有计划支持苹果芯片。

**Comment by TtlyLynzie** [comment]
<img width="1019" alt="CleanShot 2022-12-04 at 16 17 15@2x" src="https://user-images.githubusercontent.com/62136973/205480924-24ee89d9-0468-499d-9c5d-44aee0b49f4a.png">
视频打不开，mkv格式视频，视频是有那种官方原生字幕的

**Comment by tangshimin** [comment]
1. 用命令行的方式打开：在 Typing Learner 的图标上，按鼠标右键 > 选择显示包内容 > 进入 Contents > 进入 MacOS > 然后双击 Typing Learner
2. 然后再把视频拖进来，然后给我看一下命令行报错。

**Comment by tangshimin** [comment]
1. 用命令行的方式启动：在 Typing Learner 的图标上，按鼠标右键 > 选择显示包内容 > 进入 Contents > 进入 MacOS > 然后双击 Typing Learner
2. 然后再把视频拖到抄写字幕界面，然后给我看一下命令行报错。

**Comment by TtlyLynzie** [comment]
可以运行了，是我有个地方点错了。谢谢！
