### ISSUE TITLE
是否可以加一个控制字体大小的选项？

### ISSUE THREAD

**Issue by gy-l** [tangshimin/typing-learner#13]
是否可以加一个控制字体大小的选项，字体太大，摸鱼学习的时候还是能看出来，尤其是这个单词大小，居中可以改成居右，做得更像在操作terminal,这样就完美了。
![截屏2022-05-18 上午10 47 18](https://user-images.githubusercontent.com/15245259/168947059-cc23b59d-8d7a-4d3d-8424-c16c2a312970.png)
甚至可以加terminal的文件位置在上面
![截屏2022-05-18 上午10 56 47](https://user-images.githubusercontent.com/15245259/168947963-0cd3a3fe-c000-4662-9568-71e27b701937.png)
我的要求是不是有点过分了😏

**Comment by tangshimin** [comment]
可以改变字体的大小

**Comment by gy-l** [comment]
> 可以改变字体的大小
在那里修改？我找了一圈没找到

**Comment by tangshimin** [comment]
可以加一个修改字体大小的功能，现在还没有

**Comment by tangshimin** [comment]
最新的 1.0 增加了一个调整字体样式功能， 在【词库】 > 【设置】 > 【字体样式】
