### ISSUE TITLE
增加抄書功能

### ISSUE THREAD

**Issue by GrimPixel** [tangshimin/typing-learner#15]
放入文本文檔，一句一句地打字。

**Comment by tangshimin** [comment]
抄书功能以前也想过，觉得有点复杂就放弃了，你刚刚提这个 Issue, 我又重新思考了一下，想到了一个简单的方式实现这个功能。
这个功能可能要等 1.0 发布之后再添加。

**Comment by tangshimin** [comment]
1.0 的安装包已经发布了，增加了抄写文本功能。
