### ISSUE TITLE
可以增加批量功能吗

### ISSUE THREAD

**Issue by dzshi96** [tangshimin/typing-learner#18]
我下载了1000多个TED视频，想问下 可以增加 从mkv视频批量生成词典吗？

**Comment by tangshimin** [comment]
你想合成一个词库，还是分别为每个视频生成一个词库？

**Comment by tangshimin** [comment]
可以加这个功能

**Comment by tangshimin** [comment]
我还是加一个选项吧，这样既可以批量为每个视频生成词库，又可以为多个视频生成一个词库。

**Comment by dzshi96** [comment]
都可以，谢谢大佬了

**Comment by dzshi96** [comment]
捐赠了一点绵薄之力，大佬可以优先开发这个功能吗

**Comment by tangshimin** [comment]
感谢捐赠！
下一版就添加。

**Comment by dzshi96** [comment]
非常感谢

**Comment by tangshimin** [comment]
你的 TED 视频是 MKV 格式吗？
每个视频都有英语字幕吗？

**Comment by dzshi96** [comment]
是的，都是非常标准的格式，mkv视频+srt字幕

**Comment by tangshimin** [comment]
是加 srt 字幕？srt 没有封装到 mkv 里面？

**Comment by dzshi96** [comment]
封装到mkv里面了

**Comment by tangshimin** [comment]
封装了就好。这些视频是在一个文件夹吗？

**Comment by dzshi96** [comment]
分文件夹存放的，不过 可以用everything搜索出来，再拖放到typing-learner里。
类似于
![image](https://user-images.githubusercontent.com/54979250/177909035-db9bc164-8124-40a0-a2e8-063fe1a8509c.png)

**Comment by dzshi96** [comment]
增加批量处理就行，全部视频都选择 0 轨道字幕 或者 1 轨道字幕

**Comment by dzshi96** [comment]
图形界面，或者命令行模式都行

**Comment by tangshimin** [comment]
好的。批量的数量限制，不可能是 1000， 1000 太多了，现在暂时定为 100。

**Comment by dzshi96** [comment]
如果做成命令行的话，可以做成这种形式
![image](https://user-images.githubusercontent.com/54979250/177909992-cf80bf0f-cc2e-4ddc-9e0d-ded19f7052f3.png)

**Comment by dzshi96** [comment]
嗯嗯，100可以的

**Comment by tangshimin** [comment]
批量生成词库功能已经写好了，但是又引入了两个 bug,所有暂时不会发布。
你现在要用的话，可以提前发给你。

**Comment by tangshimin** [comment]
这两个 bug,不会影响正常使用，只是【选择章节】和【生成词库】的预览单词区，没有垂直滚动条。

**Comment by dzshi96** [comment]
可以的，你打包成 .msi 发给我吧，发邮箱可以吗

**Comment by tangshimin** [comment]
可以。我在排队做核酸，可能要等1个小时。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月14日(星期四) 晚上6:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tangshimin/typing-learner] 可以增加批量功能吗 (Issue #18)




 
可以的，你打包成 .msi 发给我吧，发邮箱可以吗

**Comment by dzshi96** [comment]
好的

**Comment by tangshimin** [comment]
你的邮箱是多少？
如果不想发到这里，可以发一个信息到 [tang_shimin@qq.com](mailto:tang_shimin@qq.com)，我再把安装包发给你。

**Comment by dzshi96** [comment]
3409126995@qq.com

**Comment by dzshi96** [comment]
大佬，有一个问题：多个 mkv 批量生成的词库没有视频播放的 url （图左）。
若 mkv 分别生成词库，再合并是包含播放url的（图右）；
这个批量功能可以增加视频播放的 url 吗，或者修改成生成单个词库

![image](https://user-images.githubusercontent.com/54979250/178981146-4d6814d4-0ea9-4fe3-9f10-c70eedd1b86d.png)
![image](https://user-images.githubusercontent.com/54979250/178982279-7443dc4e-2046-4ab6-9c23-880bbf622c71.png)

**Comment by tangshimin** [comment]
是 bug,我马上改。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月14日(星期四) 晚上8:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tangshimin/typing-learner] 可以增加批量功能吗 (Issue #18)




 
大佬，有一个问题：多个 mkv 批量生成的词库没有视频播放的 url （图左）。
 若 mkv 分别生成词库，再合并是包含播放url的（图右）；
 这个批量功能可以增加视频播放的 url 吗，或者修改成生成单个词库
