### ISSUE TITLE
Mac版本生成词库不生效

### ISSUE THREAD

**Issue by chengxicn** [tangshimin/typing-learner#19]
Mac dmg安装包目前不在  typing-learner\resources\common\dictionary， 而在 typing-learner\resources\dictionary，且是已经解压版本。 运行生成词库功能，无论txt还是srt，分析单词都是0.

**Comment by tangshimin** [comment]
修复了，我再修一个 bug 就打包 beta16。

**Comment by chengxicn** [comment]
已验证，问题解决。非常感谢！
