### ISSUE TITLE
win64 1920 x 1080分辨率打开程序不显示菜单栏

### ISSUE THREAD

**Issue by LarryKHite** [tangshimin/typing-learner#24]
<img width="959" alt="2022-06-25_232105" src="https://user-images.githubusercontent.com/9220139/175780097-72db549f-695a-4a2a-b4f1-ac9460cddfbb.png">

每次都需要手工调整到1680 x 1050后才可以使用

**Comment by tangshimin** [comment]
你能录个视频吗？

**Comment by tangshimin** [comment]
你是不是设置了显示器【缩放】，我的显示器也是 1920 x 1080 ，【缩放】设置到 140% 也会出现不能显示菜单栏的问题。
解决方法 1 把显示器缩放调小，如果调小不方便，可以在每次启动后拖动窗口的左右两边，做一个调整窗口大小的动作，调整幅度不用很大，菜单栏就会跳出来。

https://user-images.githubusercontent.com/16540656/175781803-58bc2c5a-bdab-4d06-9ca9-61b78bcc62e4.mp4

。

**Comment by tangshimin** [comment]
新版本，启动时不会自动最大化了，会保存关闭时的状态，所以调整好窗口的大小后，下一次再启动也不用再调整窗口了。
