### ISSUE TITLE
增加快捷键删除单词

### ISSUE THREAD

**Issue by 3217333857** [tangshimin/typing-learner#41]
其实很多单词都认识，但是还要用鼠标移动去删除单词很麻烦，希望可以出个快捷键删除单词

**Comment by tangshimin** [comment]
设置成 Ctrl + Y 怎么样？距离右手的食指很近。
可用的字母不多了。

**Comment by tangshimin** [comment]
暂时不要频繁的使用那个删除按钮，现在程序有一个 bug，删除单词可能会引发程序崩溃。
没有修复之前可用使用【过滤词库】功能，批量的过滤单词，可用把熟悉的词写到一个 txt ，然后再生成词库，这样就有了一个熟悉词库，然后再批量的把熟悉单词过滤掉。

**Comment by tangshimin** [comment]
> 暂时不要频繁的使用那个删除按钮，现在程序有一个 bug，删除单词可能会引发程序崩溃。 没有修复之前可用使用【过滤词库】功能，批量的过滤单词，可用把熟悉的词写到一个 txt ，然后再生成词库，这样就有了一个熟悉词库，然后再批量的把熟悉单词过滤掉。

崩溃的概率很低，只有删除最后一个单词的时候才有可能触发。

**Comment by 3217333857** [comment]
用delete键删除如何，delete键几乎就没用到过

**Comment by tangshimin** [comment]
新版本已经发布
