### ISSUE TITLE
抄写字幕功能是不是有问题呢

### ISSUE THREAD

**Issue by 3217333857** [tangshimin/typing-learner#43]
我昨天拖入一集老友记视频，700多mb，然后程序就显示一个下拉框选择中英字幕的摆放位置，然后多了一个正在加载打不开的窗口，然后我以为是视频太大了，所以我今早拖入了一个18mb的mkv格式的ted视频，可是拖进去程序就一直在转圈，十几分钟了还是如此。

**Comment by tangshimin** [comment]
你可用重新录个视频吗？
这个bug 跟文件大小没有关系，可能跟文件的格式有关。你再换一些 mkv 的视频试一下呢？

**Comment by 3217333857** [comment]
> 

我换了另外一个美剧视频是可以的，但是觉得大部分视频都不行。。。难搞

**Comment by tangshimin** [comment]
你能不能录屏，从拖放文件到转圈的视频。

**Comment by 3217333857** [comment]
> 你能不能录屏，从拖放文件到转圈的视频。

https://lusun.com/v/GeHk9ZfhR97
我用芦笋录屏了你可以点进去看看

**Comment by tangshimin** [comment]
> > 你能不能录屏，从拖放文件到转圈的视频。
> 
> https://lusun.com/v/GeHk9ZfhR97 我用芦笋录屏了你可以点进去看看

不支持双语字幕，抄写老友记的时候选择最下面的英文字幕

**Comment by tangshimin** [comment]
你能把那个 TED 视频发给我测试一下吗？

**Comment by tangshimin** [comment]
老友记选择了【英文字幕】还不行吗？

**Comment by 3217333857** [comment]
> 老友记选择了【英文字幕】还不行吗？

是的还不行，我现在用邮箱发TED视频给你

**Comment by 3217333857** [comment]
> 你能把那个 TED 视频发给我测试一下吗？

已发送到outlook邮箱

**Comment by tangshimin** [comment]
> > 你能把那个 TED 视频发给我测试一下吗？
> 
> 已发送到outlook邮箱

找到原因了，这个字幕的格式是 WebVTT 不是常用的 SRT 格式，mkv 解析器没有识别到。

**Comment by tangshimin** [comment]
老友记的字幕是什么格式的？
老友记的字幕格式，可能也是一种不支持的格式。
老友记你是通过 bt 种子下载的吗？如果是的话把 bt 种子发到 outlook 邮箱，我下载下来测试一下。

**Comment by 3217333857** [comment]
> > > 你能把那个 TED 视频发给我测试一下吗？
> > 
> > 
> > 已发送到outlook邮箱
> 
> 找到原因了，这个字幕的格式是 WebVTT 不是常用的 SRT 格式，mkv 解析器没有识别到

> 
是通过种子下载的，我发给你

**Comment by tangshimin** [comment]
> > > > 你能把那个 TED 视频发给我测试一下吗？
> > > 
> > > 
> > > 已发送到outlook邮箱
> > 
> > 
> > 找到原因了，这个字幕的格式是 WebVTT 不是常用的 SRT 格式，mkv 解析器没有识别到
> 
> > 
> 
> 是通过种子下载的，我发给你

看到字幕格式了，是 ASS 字幕，程序本来有 ASS 字幕检测的，不知道怎么回事没有检测到。
ASS 字幕是一种常用的格式，现在 ASS 字幕解析器有问题，暂时还不支持 ASS 字幕，后面会支持 ASS 字幕。

**Comment by 3217333857** [comment]
> > > > > 你能把那个 TED 视频发给我测试一下吗？
> > > > 
> > > > 
> > > > 已发送到outlook邮箱
> > > 
> > > 
> > > 找到原因了，这个字幕的格式是 WebVTT 不是常用的 SRT 格式，mkv 解析器没有识别到
> > 
> > 
> > > 
> > 
> > 
> > 是通过种子下载的，我发给你
> 
> 看到字幕格式了，是 ASS 字幕，程序本来有 ASS 字幕检测的，不知道怎么回事没有检测到。 ASS 字幕是一种常用的格式，现在 ASS 字幕解析器有问题，暂时还不支持 ASS 字幕，后面会支持 ASS 字幕。

okok，辛苦了，你可以参考一下aboboo，这也是个英语学习软件，说不定可以给你带来灵感。

**Comment by tangshimin** [comment]
> > > > > 你能把那个 TED 视频发给我测试一下吗？
> > > > 
> > > > 
> > > > 已发送到outlook邮箱
> > > 
> > > 
> > > 找到原因了，这个字幕的格式是 WebVTT 不是常用的 SRT 格式，mkv 解析器没有识别到
> > 
> > 
> > > 
> > 
> > 
> > 是通过种子下载的，我发给你
> 
> 看到字幕格式了，是 ASS 字幕，程序本来有 ASS 字幕检测的，不知道怎么回事没有检测到。 ASS 字幕是一种常用的格式，现在 ASS 字幕解析器有问题，暂时还不支持 ASS 字幕，后面会支持 ASS 字幕。

最新版支持 ASS 字幕了，可以处理老友记里的 ASS 字幕吗？

**Comment by 3217333857** [comment]
> > > > > > 你能把那个 TED 视频发给我测试一下吗？
> > > > > 
> > > > > 
> > > > > 已发送到outlook邮箱
> > > > 
> > > > 
> > > > 找到原因了，这个字幕的格式是 WebVTT 不是常用的 SRT 格式，mkv 解析器没有识别到
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > 是通过种子下载的，我发给你
> > 
> > 
> > 看到字幕格式了，是 ASS 字幕，程序本来有 ASS 字幕检测的，不知道怎么回事没有检测到。 ASS 字幕是一种常用的格式，现在 ASS 字幕解析器有问题，暂时还不支持 ASS 字幕，后面会支持 ASS 字幕。
> 
> 最新版支持 ASS 字幕了，可以处理老友记里的 ASS 字幕吗？

failed to launch JVM,我用不了typing learner，无法测试

**Comment by tangshimin** [comment]
你的电脑是 Windows 10 还是 Windows 7?
