### ISSUE TITLE
MKV 视频解析失败，一直显示【正在读取字幕轨道列表】

### ISSUE THREAD

**Issue by tangshimin** [tangshimin/typing-learner#47]
![mkv 字幕格式](https://user-images.githubusercontent.com/16540656/177913188-e739bc83-4ac6-4b31-bd6d-35da0a9ce05f.png)

可能跟字幕的格式有关，现在只支持 SRT 格式的字幕，如果 MKV 里面封装的格式是 ASS 或其它格式的字幕可能会失败。
本来程序里有 ASS 格式检测的，但是还是有些 ASS 格式的没有检测到。

后续会支持 ASS 格式的字幕。

暂时的解决方法是：
1. 用  [FFmpeg](https://www.ffmpeg.org/) 把 MKV 视频的视频、字幕分开，然后再把字幕格式转换成 SRT，再重新合并（也可以不用合并， [使用 SRT 字幕+视频](https://github.com/tangshimin/typing-learner/wiki/%E4%BB%8E%E5%AD%97%E5%B9%95%E7%94%9F%E6%88%90%E8%AF%8D%E5%BA%93) 生成词库）。
2. 用 [FFmpeg](https://www.ffmpeg.org/) 或 [格式工厂](http://www.pcfreetime.com/formatfactory/CN/index.html) 或者 [MKVToolNix](https://mkvtoolnix.download/) 添加一个 SRT 字幕到 MKV 视频。（这个方法我没有试过，应该可行）

**Comment by sailing178** [comment]
可惜不支持ASS，自己收录的美剧都会使用特效字幕

**Comment by tangshimin** [comment]
后续版本会支持 ASS, 现在暂时可以 [使用 SRT 字幕+视频](https://github.com/tangshimin/typing-learner/wiki/%E4%BB%8E%E5%AD%97%E5%B9%95%E7%94%9F%E6%88%90%E8%AF%8D%E5%BA%93) 生成词库。
如果使用的是 MKV + SRT 生成词库，并且 MKV 默认的字幕轨道不是英语，需要用记事本打开词库，然后把第 7 行的轨道 ID 改成 -1。还可以使用[MKVToolNix](https://mkvtoolnix.download/)把 MKV 的字幕轨道设置成英语。
