### ISSUE TITLE
视频播放黑屏

### ISSUE THREAD

**Issue by Harris-Shelby** [tangshimin/typing-learner#53]
<img width="965" alt="截屏2022-07-14 11 55 16" src="https://user-images.githubusercontent.com/56914202/178895352-159fdb4b-84c0-47d9-b3a7-1734a348d4b0.png">
mkv视频播放黑屏

**Comment by tangshimin** [comment]
有声音吗？

**Comment by tangshimin** [comment]
你用命令行的方式启动，然后再试着播放，看播放视频时，命令行有没有增加什么信息？

用命令行启动的步骤：
在 Typing Learner 的图标上，按鼠标右键 > 选择显示包内容 > 进入 Contents > 进入 MacOS > 然后双击 Typing Learner

**Comment by Harris-Shelby** [comment]
<img width="1440" alt="截屏2022-07-14 21 03 31" src="https://user-images.githubusercontent.com/56914202/178989012-7684c5ae-f817-4cf0-a990-1d13103677df.png">
有声音，但是没有图像

**Comment by Harris-Shelby** [comment]
Jul 14, 2022 9:12:05 PM com.sun.jna.Native$1 uncaughtException
警告: JNA: Callback uk.co.caprica.vlcj.player.embedded.videosurface.CallbackVideoSurface$SetupCallback@29544bb7 threw the following exception
java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.player.embedded.videosurface.ByteBufferFactory
	at uk.co.caprica.vlcj.player.embedded.videosurface.NativeBuffers.allocate(NativeBuffers.java:74)
	at uk.co.caprica.vlcj.player.embedded.videosurface.CallbackVideoSurface$SetupCallback.format(CallbackVideoSurface.java:93)

**Comment by Harris-Shelby** [comment]
<img width="725" alt="截屏2022-07-14 21 15 22" src="https://user-images.githubusercontent.com/56914202/178991092-5d3b5bc2-547f-4540-a02f-8eb39f724d32.png">

VLC版本：Version 3.0.17.3 Vetinari (Intel 64bit)

**Comment by Harris-Shelby** [comment]
黑苹果

**Comment by tangshimin** [comment]
这个 bug 我也不知道怎么处理。

**Comment by peng051410** [comment]
我的苹果是Intel的，也是出现这个错误，真的无解了吗？

**Comment by tangshimin** [comment]
加 Issue 置顶的 QQ 群，试一下群里测试版。

**Comment by peng051410** [comment]
> 加 Issue 置顶的 QQ 群，试一下群里测试版。

已加

**Comment by tangshimin** [comment]
@Harris-Shelby 进置顶 QQ 群试一下最新版，好像可以了。
