### ISSUE TITLE
问题：导入的mkv没有字幕

### ISSUE THREAD

**Issue by lion-no-back** [tangshimin/typing-learner#62]
mp4格式转为mkv，查看了两个格式下的视频都有字幕，但导入Typing Leaner ，显示视频无字幕
![image](https://user-images.githubusercontent.com/100990301/179441256-d9baa8ff-5f2b-4597-951c-b5cb1bc43e3b.png)

**Comment by tangshimin** [comment]
你现在用的那个版本？是最新版吗？

**Comment by lion-no-back** [comment]
是的，最新版，刚更新的，上一版本也是这样的情况，于是等了等，看看这个问题最新版是否会解决，发现还是这样的问题

**Comment by tangshimin** [comment]
你用什么操作系统？

**Comment by lion-no-back** [comment]
![image](https://user-images.githubusercontent.com/100990301/179442049-460fc0c1-451b-47fb-9855-11dc13135b63.png)
![image](https://user-images.githubusercontent.com/100990301/179442125-60571114-57ed-4907-94b3-6cb10f4e2023.png)
![image](https://user-images.githubusercontent.com/100990301/179442209-4d694dbf-2ead-4ee9-8671-5c1ad726b036.png)
搞错了，上次是mp4,这次是rmvb,我用的是win11

**Comment by tangshimin** [comment]
这可能是字幕格式的问题。
在 PotPlayer 的播放窗口，单击右键 > 选择属性 > 文件信息，查看字幕格式。
![mkv-subtitles-format](https://user-images.githubusercontent.com/16540656/179442619-b40dfbb3-b5ce-484c-aec9-31e09c0bd7ff.png)

**Comment by tangshimin** [comment]
> 这可能是字幕格式的问题。 在 PotPlayer 的播放窗口，单击右键 > 选择属性 > 文件信息，查看字幕格式。 ![mkv-subtitles-format](https://user-images.githubusercontent.com/16540656/179442619-b40dfbb3-b5ce-484c-aec9-31e09c0bd7ff.png)

如果字幕格式不是 SRT 或 ASS, 需要使用 FFmpeg 转换字幕格式，再重新封装成 MKV。

**Comment by lion-no-back** [comment]
没有Text选项
![2022-07-18_115749](https://user-images.githubusercontent.com/100990301/179443483-c370911e-bb0d-4d30-b5e1-254f4d4f4eab.png)

**Comment by tangshimin** [comment]
没有 Text 选项，可能在转换的过程中丢失了。
你用什么工具转换格式的？

**Comment by lion-no-back** [comment]
转化工具格式工厂，还有就是转换前也没有Text选项，但都有字幕显示的，很奇怪

**Comment by tangshimin** [comment]
在`输出配置` 里面设置，把保留所有源输入流（字幕）设置为 `是`

![mkv-subtitles-format-2](https://user-images.githubusercontent.com/16540656/179443872-dca66c58-3930-4eb4-a5bb-ba59ddff5e8f.png)

**Comment by tangshimin** [comment]
如果你想转换的快一点，可以把解码器设置为 `复制流`
![mkv-subtitles-format-3](https://user-images.githubusercontent.com/16540656/179444293-e2a8edef-2bbc-45d6-ba3e-99e7f142432e.png)

**Comment by lion-no-back** [comment]
还是不可以
![image](https://user-images.githubusercontent.com/100990301/179444535-6cf0f9c4-b2d6-4d94-8c4b-eb91abc0b994.png)
![image](https://user-images.githubusercontent.com/100990301/179444582-ac879627-eb20-4d28-9d0a-228ad3448e08.png)

**Comment by tangshimin** [comment]
> 

用 PotPlayer 查看有没有字幕

**Comment by tangshimin** [comment]
> 还是不可以 ![image](https://user-images.githubusercontent.com/100990301/179444535-6cf0f9c4-b2d6-4d94-8c4b-eb91abc0b994.png) ![image](https://user-images.githubusercontent.com/100990301/179444582-ac879627-eb20-4d28-9d0a-228ad3448e08.png)

`其它` 那一栏的截图是怎么样的，给我看一下。

**Comment by tangshimin** [comment]
> 

字幕是不是在同一个文件夹里，PotPlayer 自动加载的字幕。

**Comment by lion-no-back** [comment]
没有，就纯粹的一个视频，视频格式是rmvb

**Comment by lion-no-back** [comment]
最为主要的有两点，一点是视频怎么找寻合适的，我的话是百度网盘有个群专门分享英美剧的，还有一些英美剧app，再加上B站可以下载，想问下你的视频来源出处，我去找下，排除下是视频的问题，另一点是只能是mkv视频格式嘛，因为我用B站下的英剧，mp4格式，然后格式工厂转为mkv，导入都不行，而且这些视频都有字幕，mkv视频格式很难下的，只能通过转换，转换后我发现都有字幕，一导入就没有字幕，感觉这个对我来说是个大问题

**Comment by tangshimin** [comment]
没有字幕，可以单独到 [SubHD](https://subhd.tv/) 下载，国内字幕组制作的字幕都会上传到这个网站，也可以在这个网站找到片源。

资源下载推荐 rarbg，网址可以自行搜索，有各种不用翻墙的镜像网址。

BT 资源搜索推荐 [iDope](https://idope.se/) 界面简洁没有广告。

BT 资源下载推荐 qBittorrent，开源软件，不会像迅雷一样限速，下载的时候选择先下载首尾文件块，下载好首尾文件块就可以播放了，再设置按顺序下载，就可以一边下载一边播放。

**Comment by tangshimin** [comment]
> 最为主要的有两点，一点是视频怎么找寻合适的，我的话是百度网盘有个群专门分享英美剧的，还有一些英美剧app，再加上B站可以下载，想问下你的视频来源出处，我去找下，排除下是视频的问题，另一点是只能是mkv视频格式嘛，因为我用B站下的英剧，mp4格式，然后格式工厂转为mkv，导入都不行，而且这些视频都有字幕，mkv视频格式很难下的，只能通过转换，转换后我发现都有字幕，一导入就没有字幕，感觉这个对我来说是个大问题

可以在群里面帮忙推荐 Typing Learner 吗？

**Comment by tangshimin** [comment]
这个可能是硬字幕，字幕嵌入到视频了，你可以再单独下载字幕，然后使用[从字幕生成词库](https://github.com/tangshimin/typing-learner/wiki/%E4%BB%8E%E5%AD%97%E5%B9%95%E7%94%9F%E6%88%90%E8%AF%8D%E5%BA%93)。

![image](https://user-images.githubusercontent.com/16540656/179452564-04a06de0-b764-46fe-866f-4720f9eed43e.png)

**Comment by lion-no-back** [comment]
应该是内嵌字幕，使用字幕生成词库，发现并没有那么好用，为了测试，我从[SubHD](https://subhd.tv/)下载老友记字幕，格式为ass，然后利用[字幕在线转换工具](https://convert.jamack.net/zh/convert/srt/%E8%AF%B7%E5%85%88%E9%80%89%E6%8B%A9%E5%AD%97%E5%B9%95%E6%96%87%E4%BB%B6%E3%80%82),转为srt

然后查看字幕文件没有问题，于是使用字幕生成词库，字幕为srt格式，视频为mkv，出现了两种情况，唯独没有成功过
![1](https://user-images.githubusercontent.com/100990301/179487554-765649ec-8aed-400a-8439-0faf032d00b4.png)
![3](https://user-images.githubusercontent.com/100990301/179487578-78f6c182-409b-49ab-ada5-9e62b4142556.png)

时机不成熟，暂时不搞了，等用的人多了应该功能就会优化，期待

**Comment by tangshimin** [comment]
> 应该是内嵌字幕，使用字幕生成词库，发现并没有那么好用，为了测试，我从[SubHD](https://subhd.tv/)下载老友记字幕，格式为ass，然后利用[字幕在线转换工具](https://convert.jamack.net/zh/convert/srt/%E8%AF%B7%E5%85%88%E9%80%89%E6%8B%A9%E5%AD%97%E5%B9%95%E6%96%87%E4%BB%B6%E3%80%82),转为srt
> 
> 然后查看字幕文件没有问题，于是使用字幕生成词库，字幕为srt格式，视频为mkv，出现了两种情况，唯独没有成功过 ![1](https://user-images.githubusercontent.com/100990301/179487554-765649ec-8aed-400a-8439-0faf032d00b4.png) ![3](https://user-images.githubusercontent.com/100990301/179487578-78f6c182-409b-49ab-ada5-9e62b4142556.png)
> 
> 时机不成熟，暂时不搞了，等用的人多了应该功能就会优化，期待

不能使用字幕生成词库修复了，可以下载最新版试一下。

**Comment by lion-no-back** [comment]
我刚下载最新版试了下，发现可以了

![1658803179926](https://user-images.githubusercontent.com/100990301/180911453-9ec4ac27-cae2-4ab2-bc50-a3e63ce9789f.png)

有个疑惑，就保存的文件类型为所有，这个就是单纯保存生成的词库吗?还有就是我用字幕生成词库后保存了文件，我把字幕文件及视频删掉应该没有影响吧
---

说一下我这次操作的过程，首先我用闪豆下载器下载了B站老友记第一集，然后去了[SubHD](https://subhd.tv)下载了字幕文件，格式为ass，然后去了[歌词字幕在线转换器](http://www.lrccon.com/convert.php)，转为srt文件，然后用字幕生成词库，字幕文件格式为srt，视频为mp4，然后貌似成功了

**Comment by tangshimin** [comment]
> 我刚下载最新版试了下，发现可以了
> 
> ![1658803179926](https://user-images.githubusercontent.com/100990301/180911453-9ec4ac27-cae2-4ab2-bc50-a3e63ce9789f.png)
> ## 有个疑惑，就保存的文件类型为所有，这个就是单纯保存生成的词库吗?还有就是我用字幕生成词库后保存了文件，我把字幕文件及视频删掉应该没有影响吧
> 
> 说一下我这次操作的过程，首先我用闪豆下载器下载了B站老友记第一集，然后去了[SubHD](https://subhd.tv)下载了字幕文件，格式为ass，然后去了[歌词字幕在线转换器](http://www.lrccon.com/convert.php)，转为srt文件，然后用字幕生成词库，字幕文件格式为srt，视频为mp4，然后貌似成功了

字幕可以删除，视频不能删除，也不能移动，最好把视频放到一个固定的位置。

**Comment by lion-no-back** [comment]
好家伙，刚把视频字幕删了，不过没关系，测试用的，那OK，非常nice的一款工具，希望继续优化下去，帮助更多人(如果开发者有精力和时间的话)

**Comment by tangshimin** [comment]
> 说一下我这次操作的过程，首先我用闪豆下载器下载了B站老友记第一集，然后去了[SubHD](https://subhd.tv/)下载了字幕文件，格式为ass，然后去了[歌词字幕在线转换器](http://www.lrccon.com/convert.php)，转为srt文件，然后用字幕生成词库，字幕文件格式为srt，视频为mp4，然后貌似成功了

B站的视频，可能有删减，可能和 SubHD 的字幕不匹配。
好像 SubHD 有没有删减的老友记。

**Comment by lion-no-back** [comment]
这样的视频资源好找，只不过B站一搜就有，虽说要vip，但很多脚本都可以实现解析观看，所以拿它试验，至于SubHD有，我看了下，貌似是一季打包好了，几个G，还要关注公众号，完全没必要，像这样的资源，直接去那种网盘资源站点，很多未删减资源都有，昨天浏览了下，发现什么万物生长未删减版，什么慈禧私照啥玩意儿，影视资源倒不是问题
