### ISSUE TITLE
视频字幕可以优化一下吗？

### ISSUE THREAD

**Issue by dzshi96** [tangshimin/typing-learner#65]
优化前：现在的视频字幕不能选中；
优化后：双击字幕可以选择某一单词，鼠标悬浮时，选中的单词会自动发音并显示音标。（这样就不用每次都手敲一遍，再去查音标了）
![image](https://user-images.githubusercontent.com/54979250/179519645-1592ac20-4539-4e1e-8dda-43cc276ab3e6.png)

**Comment by tangshimin** [comment]
升级到最新版，点击【帮助文档】&gt; 【快捷键】&gt;查看激活复制。
复制单词后再按 Ctrl + F 查询单词。查询后可以按 Ctrl +J 播放单词的发音。


现有的 API 还不能实现，选择后自动查询单词。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月18日(星期一) 晚上9:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tangshimin/typing-learner] 视频字幕可以优化一下吗？ (Issue #65)




 
优化前：现在的视频字幕不能选中；
 优化后：双击字幕可以选择某一单词，鼠标悬浮时，选中的单词会自动发音并显示音标。（这样就不用每次都手敲一遍，再去查音标了）
