### ISSUE TITLE
可以增加用户自定义快捷键吗？

### ISSUE THREAD

**Issue by dzshi96** [tangshimin/typing-learner#66]
![image](https://user-images.githubusercontent.com/54979250/179665651-c997d9a0-e00f-4e4f-b313-6f0d04ba7948.png)

**Comment by tangshimin** [comment]
用户自定义快捷键，会引起冲突。不好写。

是某个快捷键跟你常用的快捷键有冲突吗？

**Comment by dzshi96** [comment]
没有冲突，只是觉得有些按键不好按。
