### ISSUE TITLE
运行时间长了反应会很慢。

### ISSUE THREAD

**Issue by tangshimin** [tangshimin/typing-learner#69]
记忆单词界面，运行时间超过 1 个小时，反应会变慢。
还没找到原因，感觉跟速度组件有关。

想把速度组件删除了。

**Comment by tangshimin** [comment]
输入明明是正确的，却被判断为错误。

**Comment by tangshimin** [comment]
暂时的解决办法是重新启动应用程序。

**Comment by cksdevelop** [comment]
写下一条建议:建议业余时间每天学习半小时.

**Comment by tangshimin** [comment]
> 写下一条建议:建议业余时间每天学习半小时.

哈哈哈 bug 变 features。

**Comment by tangshimin** [comment]
跟速度组件无关，速度组件已经删除了，使用时间长了还是会触发这个 bug。

**Comment by tangshimin** [comment]
相关 Issue: https://github.com/JetBrains/compose-jb/issues/1969,
我以为是输入处理的函数有问题，调试了几天，这个问题很严重，应该会很快修复。

**Comment by tangshimin** [comment]
相关 Issue:  compose-jb/issues/1969,
我以为是输入处理的函数有问题，调试了几天，这个问题很严重，应该会很快修复。
