### ISSUE TITLE
【生成词库】相同单词不删除而是记录为新例句

### ISSUE THREAD

**Issue by ybingo** [tangshimin/typing-learner#70]
生成词库的时候，能不能实现这样一个效果：先从字幕里匹配出所有包含在词库中的单词，对于相同的单词不删除，而是记录其出现位置的例句，最后生成的词库按时间轴顺序排列，且不同位置的相同单词例句不同。

**Comment by tangshimin** [comment]
你觉得这个功能应该叫什么名字？
这个功能跟 [链接字幕词库](https://github.com/tangshimin/typing-learner/wiki/%E9%93%BE%E6%8E%A5%E5%AD%97%E5%B9%95%E8%AF%8D%E5%BA%93) 很像。

**Comment by ybingo** [comment]
链接字幕词库是依赖于根据字幕生成的词库，而这个词库每个单词只匹配 3 条例句。能不能按照时间轴，每个单词匹配自定义数量的例句呢？如果这个功能能实现的话，可不可以更进一步，按照例句的时间轴来排序单词，这样一边背单词还可以一边按照正常的时间顺序看完一个视频。

**Comment by tangshimin** [comment]
> 按照例句的时间轴来排序单词，这样一边背单词还可以一边按照正常的时间顺序看完一个视频。

如果你在生成词库的使用不做任何的过滤，直接保存，在记忆单词的时候，遇到熟悉的词直接跳过，就能达到这种效果。
