### ISSUE TITLE
能增加雅思的词库吗？

### ISSUE THREAD

**Issue by LarryKHite** [tangshimin/typing-learner#74]
最近几个版本越来越好用了，建议能否增加雅思的词库？非常感谢 😃

**Comment by tangshimin** [comment]
> 最近几个版本越来越好用了，建议能否增加雅思的词库？非常感谢 😃
在大学英语里面有一个 IELTS 词库

**Comment by tangshimin** [comment]
在大学英语里面有一个 IELTS 词库

**Comment by tangshimin** [comment]
要不要下一个版本把 IELTS 和 TOEFL 都改成中文简称？

**Comment by LarryKHite** [comment]
> 要不要下一个版本把 IELTS 和 TOEFL 都改成中文简称？

没必要，要学的人都知道简称
