### ISSUE TITLE
能不能增加调整所有字体大小的选项？

### ISSUE THREAD

**Issue by zhl111** [tangshimin/typing-learner#80]
1，字体变大易于识别，尤其是单词下面的解释部分。需要费力识别，可以根据个人需要放大到余光即能识别的地步
2，一些年纪打的父母老人也很感兴趣这个软件，能否考虑下他们的需求？
3，对于熟悉的单词，如果选择忽略，是选择删除吗？但我不想真的删除单词，我只是想忽略，剩下的单词不就是困难的了吗？或者说用“熟悉-不熟悉”，是否比“困难”心理压力小点？
非常感谢您的付出

**Comment by tangshimin** [comment]
1. 【调整单词下面部分的字体大小】可能会在下一个版本添加。
2. 真的有老年人用这个软件？还有什么特殊需求吗？
3. 熟悉的单词可以用 Enter 键跳过啊。
