### ISSUE TITLE
为什么会提示病毒？

### ISSUE THREAD

**Issue by zhl111** [tangshimin/typing-learner#81]
导致我电脑重启……

![image](https://user-images.githubusercontent.com/29135984/181595619-104c27d0-7500-4b33-829f-560fd1e66bdf.png)

**Comment by tangshimin** [comment]
【了解更多信息】点了之后会出现什么？

**Comment by tangshimin** [comment]
这是那个软件报的警告?
v1.3.6 下载了150 次，你是第一个出现这个警告的用户。

**Comment by tangshimin** [comment]
我刚刚把 Typing-Learner-1.3.6.msi 上传到 VirusTotal 进行检测，没有发现病毒：https://www.virustotal.com/gui/file/c093d81eefb42147ddc47680cfd08c556d4e08467242bc333294a18036af099e/detection

![image](https://user-images.githubusercontent.com/16540656/181602705-c9610821-944d-4838-ba9a-b3b638dc49a5.png)

**Comment by tangshimin** [comment]
用火绒的【自定义查杀】也没有发现风险。

**Comment by tangshimin** [comment]
可能是误报，你用搜索引擎搜索【windows defender 误报】会搜到很多相关信息

**Comment by tangshimin** [comment]
你要不要把你下载的那个安装包也上传到：https://www.virustotal.com/gui/home/upload 检测一下。

**Comment by tangshimin** [comment]
上传之后还要看 SHA-256 是不是一样的。

![v1 3 6 SHA256](https://user-images.githubusercontent.com/16540656/181678683-ea073fc7-324b-4214-9a84-6a0cd9430bf0.png)
