### ISSUE TITLE
打开词库，浏览并删除单词时，可否增加一个不需要确认的选项

### ISSUE THREAD

**Issue by heisaari** [tangshimin/typing-learner#86]
如题，过滤词库那里字很小所以在目前打开词库这里过滤，遇到的问题是每次删除都需要确认下，能否增加个不需要确认的选项

另外希望这个界面里释义字体也能调大些

**Comment by tangshimin** [comment]
删除操作不可逆，有时候鼠标会点错，或者键盘按错。所以这里不会改。
你可以用快捷键 Delete 删除，然后按快捷键 Y 快速确认，不使用鼠标。

释义字体调整，下一个版本会添加。
