### ISSUE TITLE
releases上可以提供一个便携版（zip格式）吗？

### ISSUE THREAD

**Issue by dzshi96** [tangshimin/typing-learner#89]

**Comment by tangshimin** [comment]
你想要一个便携版，放U盘？
还是要一个 zip 格式的安装包？

**Comment by dzshi96** [comment]
可以放U盘的，我用dropbox同步

**Comment by tangshimin** [comment]
现在可以放到 U 盘，如果你要用 dropbox 同步，可能需要同步两个文件夹：
打开【帮助】-> 【帮助文档】-> 选择左侧最下面的【特殊文件夹】,然后就可以打开对应的特殊文件夹。
可能需要同步【安装目录 】`Typing Learner` 和 【配置文件夹】  `.typing-learner`

**Comment by dzshi96** [comment]
用安装版就可以是吧，只需要同步【安装目录 】、【配置文件夹】就可以了？

**Comment by tangshimin** [comment]
对，我刚刚把我的 【安装目录】复制到 U盘，然后，卸载了 Typing Learner ，试了一下可以从 U盘启动。
但是配置文件的地址还是固定的，不能移动。

**Comment by dzshi96** [comment]
嗯嗯，好的，非常感谢
