### ISSUE TITLE
遇到一个问题，卸载了重装还是一样一打开就报这个错误

### ISSUE THREAD

**Issue by gy-l** [tangshimin/typing-learner#93]
Can't represent a size of 505248 in Constraints,理解是不是因为字幕太长了超过了限制？但为何卸载重装还是一样的报错？卸载完成的时候我去application和cache里看过都没有残留
![截屏2022-10-17 上午10 09 43](https://user-images.githubusercontent.com/15245259/196074796-a4a444f3-551c-4076-8541-17f887d6246d.png)

**Comment by tangshimin** [comment]
暂时还不支持 WEBVTT 格式的字幕。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月17日(周一) 上午10:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tangshimin/typing-learner] 遇到一个问题，卸载了重装还是一样一打开就报这个错误 (Issue #93)




 
Can't represent a size of 505248 in Constraints,理解是不是因为字幕太长了超过了限制？但为何卸载重装还是一样的报错？卸载的时候我去application和cache里看过都没有残留
